//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MONO.Order.Test.CU0531Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", ConfigurationName="CU0531Reference.FWPInfServiceImpl")]
    public interface FWPInfServiceImpl {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MONO.Order.Test.CU0531Reference.orderSubResponse orderSub(MONO.Order.Test.CU0531Reference.orderSub request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MONO.Order.Test.CU0531Reference.hasOrderSuccResponse hasOrderSucc(MONO.Order.Test.CU0531Reference.hasOrderSucc request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxyResponse setNewProductOrderServiceProxy(MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxy request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        MONO.Order.Test.CU0531Reference.setWoPlusServiceproxyResponse setWoPlusServiceproxy(MONO.Order.Test.CU0531Reference.setWoPlusServiceproxy request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class fwpOrderSubReq : request {
        
        private string orderNoField;
        
        private int productIdField;
        
        private int sendMessageField;
        
        private int valid2GField;
        
        private int valid3GField;
        
        private int valid4GField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int sendMessage {
            get {
                return this.sendMessageField;
            }
            set {
                this.sendMessageField = value;
                this.RaisePropertyChanged("sendMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int valid2G {
            get {
                return this.valid2GField;
            }
            set {
                this.valid2GField = value;
                this.RaisePropertyChanged("valid2G");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int valid3G {
            get {
                return this.valid3GField;
            }
            set {
                this.valid3GField = value;
                this.RaisePropertyChanged("valid3G");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int valid4G {
            get {
                return this.valid4GField;
            }
            set {
                this.valid4GField = value;
                this.RaisePropertyChanged("valid4G");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fwpHasOrderSuccReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fwpOrderSubReq))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string channelCodeField;
        
        private string infMethodNameField;
        
        private string infUserNameField;
        
        private string infUserPwdField;
        
        private string mediaInfoField;
        
        private string memberIdField;
        
        private string memberPwdField;
        
        private para[] parasField;
        
        private string serialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string channelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
                this.RaisePropertyChanged("channelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string infMethodName {
            get {
                return this.infMethodNameField;
            }
            set {
                this.infMethodNameField = value;
                this.RaisePropertyChanged("infMethodName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string infUserName {
            get {
                return this.infUserNameField;
            }
            set {
                this.infUserNameField = value;
                this.RaisePropertyChanged("infUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string infUserPwd {
            get {
                return this.infUserPwdField;
            }
            set {
                this.infUserPwdField = value;
                this.RaisePropertyChanged("infUserPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mediaInfo {
            get {
                return this.mediaInfoField;
            }
            set {
                this.mediaInfoField = value;
                this.RaisePropertyChanged("mediaInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string memberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
                this.RaisePropertyChanged("memberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string memberPwd {
            get {
                return this.memberPwdField;
            }
            set {
                this.memberPwdField = value;
                this.RaisePropertyChanged("memberPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paras", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public para[] paras {
            get {
                return this.parasField;
            }
            set {
                this.parasField = value;
                this.RaisePropertyChanged("paras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class para : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paraIdField;
        
        private string paraValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paraId {
            get {
                return this.paraIdField;
            }
            set {
                this.paraIdField = value;
                this.RaisePropertyChanged("paraId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string paraValue {
            get {
                return this.paraValueField;
            }
            set {
                this.paraValueField = value;
                this.RaisePropertyChanged("paraValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class woPlusBSSGWServiceProxy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endpointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
                this.RaisePropertyChanged("endpoint");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class newProductOrderServiceProxy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endpointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
                this.RaisePropertyChanged("endpoint");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fwpHasOrderSuccResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fwpOrderSubResp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descField;
        
        private string mediaInfoField;
        
        private para[] parasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mediaInfo {
            get {
                return this.mediaInfoField;
            }
            set {
                this.mediaInfoField = value;
                this.RaisePropertyChanged("mediaInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paras", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public para[] paras {
            get {
                return this.parasField;
            }
            set {
                this.parasField = value;
                this.RaisePropertyChanged("paras");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class fwpHasOrderSuccResp : response {
        
        private string hasOrderField;
        
        private string mobileField;
        
        private int netTypeField;
        
        private string orderDescField;
        
        private string orderNoField;
        
        private int productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hasOrder {
            get {
                return this.hasOrderField;
            }
            set {
                this.hasOrderField = value;
                this.RaisePropertyChanged("hasOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int netType {
            get {
                return this.netTypeField;
            }
            set {
                this.netTypeField = value;
                this.RaisePropertyChanged("netType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string orderDesc {
            get {
                return this.orderDescField;
            }
            set {
                this.orderDescField = value;
                this.RaisePropertyChanged("orderDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class fwpOrderSubResp : response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.wpip.bcinfo.com/")]
    public partial class fwpHasOrderSuccReq : request {
        
        private string orderNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="orderSub", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class orderSub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.fwpOrderSubReq arg0;
        
        public orderSub() {
        }
        
        public orderSub(MONO.Order.Test.CU0531Reference.fwpOrderSubReq arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="orderSubResponse", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class orderSubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.fwpOrderSubResp @return;
        
        public orderSubResponse() {
        }
        
        public orderSubResponse(MONO.Order.Test.CU0531Reference.fwpOrderSubResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasOrderSucc", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class hasOrderSucc {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.fwpHasOrderSuccReq arg0;
        
        public hasOrderSucc() {
        }
        
        public hasOrderSucc(MONO.Order.Test.CU0531Reference.fwpHasOrderSuccReq arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hasOrderSuccResponse", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class hasOrderSuccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.fwpHasOrderSuccResp @return;
        
        public hasOrderSuccResponse() {
        }
        
        public hasOrderSuccResponse(MONO.Order.Test.CU0531Reference.fwpHasOrderSuccResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewProductOrderServiceProxy", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class setNewProductOrderServiceProxy {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.newProductOrderServiceProxy arg0;
        
        public setNewProductOrderServiceProxy() {
        }
        
        public setNewProductOrderServiceProxy(MONO.Order.Test.CU0531Reference.newProductOrderServiceProxy arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNewProductOrderServiceProxyResponse", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class setNewProductOrderServiceProxyResponse {
        
        public setNewProductOrderServiceProxyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setWoPlusServiceproxy", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class setWoPlusServiceproxy {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.wpip.bcinfo.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MONO.Order.Test.CU0531Reference.woPlusBSSGWServiceProxy arg0;
        
        public setWoPlusServiceproxy() {
        }
        
        public setWoPlusServiceproxy(MONO.Order.Test.CU0531Reference.woPlusBSSGWServiceProxy arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setWoPlusServiceproxyResponse", WrapperNamespace="http://impl.service.wpip.bcinfo.com/", IsWrapped=true)]
    public partial class setWoPlusServiceproxyResponse {
        
        public setWoPlusServiceproxyResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FWPInfServiceImplChannel : MONO.Order.Test.CU0531Reference.FWPInfServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FWPInfServiceImplClient : System.ServiceModel.ClientBase<MONO.Order.Test.CU0531Reference.FWPInfServiceImpl>, MONO.Order.Test.CU0531Reference.FWPInfServiceImpl {
        
        public FWPInfServiceImplClient() {
        }
        
        public FWPInfServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FWPInfServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FWPInfServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FWPInfServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MONO.Order.Test.CU0531Reference.orderSubResponse MONO.Order.Test.CU0531Reference.FWPInfServiceImpl.orderSub(MONO.Order.Test.CU0531Reference.orderSub request) {
            return base.Channel.orderSub(request);
        }
        
        public MONO.Order.Test.CU0531Reference.fwpOrderSubResp orderSub(MONO.Order.Test.CU0531Reference.fwpOrderSubReq arg0) {
            MONO.Order.Test.CU0531Reference.orderSub inValue = new MONO.Order.Test.CU0531Reference.orderSub();
            inValue.arg0 = arg0;
            MONO.Order.Test.CU0531Reference.orderSubResponse retVal = ((MONO.Order.Test.CU0531Reference.FWPInfServiceImpl)(this)).orderSub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MONO.Order.Test.CU0531Reference.hasOrderSuccResponse MONO.Order.Test.CU0531Reference.FWPInfServiceImpl.hasOrderSucc(MONO.Order.Test.CU0531Reference.hasOrderSucc request) {
            return base.Channel.hasOrderSucc(request);
        }
        
        public MONO.Order.Test.CU0531Reference.fwpHasOrderSuccResp hasOrderSucc(MONO.Order.Test.CU0531Reference.fwpHasOrderSuccReq arg0) {
            MONO.Order.Test.CU0531Reference.hasOrderSucc inValue = new MONO.Order.Test.CU0531Reference.hasOrderSucc();
            inValue.arg0 = arg0;
            MONO.Order.Test.CU0531Reference.hasOrderSuccResponse retVal = ((MONO.Order.Test.CU0531Reference.FWPInfServiceImpl)(this)).hasOrderSucc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxyResponse MONO.Order.Test.CU0531Reference.FWPInfServiceImpl.setNewProductOrderServiceProxy(MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxy request) {
            return base.Channel.setNewProductOrderServiceProxy(request);
        }
        
        public void setNewProductOrderServiceProxy(MONO.Order.Test.CU0531Reference.newProductOrderServiceProxy arg0) {
            MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxy inValue = new MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxy();
            inValue.arg0 = arg0;
            MONO.Order.Test.CU0531Reference.setNewProductOrderServiceProxyResponse retVal = ((MONO.Order.Test.CU0531Reference.FWPInfServiceImpl)(this)).setNewProductOrderServiceProxy(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MONO.Order.Test.CU0531Reference.setWoPlusServiceproxyResponse MONO.Order.Test.CU0531Reference.FWPInfServiceImpl.setWoPlusServiceproxy(MONO.Order.Test.CU0531Reference.setWoPlusServiceproxy request) {
            return base.Channel.setWoPlusServiceproxy(request);
        }
        
        public void setWoPlusServiceproxy(MONO.Order.Test.CU0531Reference.woPlusBSSGWServiceProxy arg0) {
            MONO.Order.Test.CU0531Reference.setWoPlusServiceproxy inValue = new MONO.Order.Test.CU0531Reference.setWoPlusServiceproxy();
            inValue.arg0 = arg0;
            MONO.Order.Test.CU0531Reference.setWoPlusServiceproxyResponse retVal = ((MONO.Order.Test.CU0531Reference.FWPInfServiceImpl)(this)).setWoPlusServiceproxy(inValue);
        }
    }
}
